/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AiMatchingRouteImport } from './routes/ai-matching'
import { Route as IndexRouteImport } from './routes/index'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchingRoute = AiMatchingRouteImport.update({
  id: '/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/skills': typeof SkillsRoute
  '/talent': typeof TalentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/skills': typeof SkillsRoute
  '/talent': typeof TalentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/skills': typeof SkillsRoute
  '/talent': typeof TalentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-matching'
    | '/insights'
    | '/marketplace'
    | '/skills'
    | '/talent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-matching'
    | '/insights'
    | '/marketplace'
    | '/skills'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/ai-matching'
    | '/insights'
    | '/marketplace'
    | '/skills'
    | '/talent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMatchingRoute: typeof AiMatchingRoute
  InsightsRoute: typeof InsightsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SkillsRoute: typeof SkillsRoute
  TalentRoute: typeof TalentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-matching': {
      id: '/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMatchingRoute: AiMatchingRoute,
  InsightsRoute: InsightsRoute,
  MarketplaceRoute: MarketplaceRoute,
  SkillsRoute: SkillsRoute,
  TalentRoute: TalentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
