/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTalentRouteImport } from './routes/_authenticated/talent'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedAiMatchingRouteImport } from './routes/_authenticated/ai-matching'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTalentRoute = AuthenticatedTalentRouteImport.update({
  id: '/_authenticated/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/_authenticated/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/_authenticated/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/_authenticated/marketplace',
    path: '/marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/_authenticated/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/_authenticated/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiMatchingRoute = AuthenticatedAiMatchingRouteImport.update({
  id: '/_authenticated/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/talent': typeof AuthenticatedTalentRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/talent': typeof AuthenticatedTalentRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/talent': typeof AuthenticatedTalentRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/ai-matching'
    | '/governance'
    | '/insights'
    | '/marketplace'
    | '/projects'
    | '/skills'
    | '/talent'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/ai-matching'
    | '/governance'
    | '/insights'
    | '/marketplace'
    | '/projects'
    | '/skills'
    | '/talent'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/admin'
    | '/_authenticated/ai-matching'
    | '/_authenticated/governance'
    | '/_authenticated/insights'
    | '/_authenticated/marketplace'
    | '/_authenticated/projects'
    | '/_authenticated/skills'
    | '/_authenticated/talent'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiMatchingRoute: typeof AuthenticatedAiMatchingRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedTalentRoute: typeof AuthenticatedTalentRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/talent': {
      id: '/_authenticated/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof AuthenticatedTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-matching': {
      id: '/_authenticated/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AuthenticatedAiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiMatchingRoute: AuthenticatedAiMatchingRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedTalentRoute: AuthenticatedTalentRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
